# Application specific deployment configuration
deployment:
  image:
    repository: globe.pe.jfrog.io/isg-omcom-docker-local-nonprod/isg-omcom/dv/lf-apirequest
    tag: master-2025-06-09-2000-e369c06
    pullPolicy: IfNotPresent
