# Application specific deployment configuration
application:
deployment:
  replicaCount: 1
  image:
    repository: globe.jfrog.io/artifactory/isg-omcom-docker-local-nonprod/lf-auth-service
    tag: master-2025-06-03-0944-89cb7a8
    pullPolicy: IfNotPresent
  containerPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: 200m
      memory: 384Mi
  env:
    MESSAGE_ENABLE: "true"
    LOG_LEVEL: info
  envFrom:
    - secretRef:
        name: lf-auth-service-configuration
    - secretRef:
        name: petal-keycloak-credentials
