{{- $selected := .Values.subchart | default "" }}
{{- range $chartName, $chart := .Subcharts }}
  {{- if or (eq $selected "") (eq $chartName $selected) }}
    {{- if $chart.Values.deployment }}
      {{- $appName := $chartName | replace "isg-omcom-cassandra-scala-services-" "" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app: {{ $appName }}
  {{- with $chart.Values.annotations | default $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $chart.Values.deployment.replicaCount | default $.Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
        app.kubernetes.io/version: {{ $chart.Values.deployment.image.tag | default $.Chart.AppVersion }}
      {{- with $chart.Values.podAnnotations | default $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with $chart.Values.nodeSelector | default $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $chart.Values.deployment.imagePullSecrets | default $.Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - emptyDir: {}
          name: heap-dumps
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: logs
        - configMap:
            defaultMode: 420
            name: {{ $appName }}
          name: config
        - configMap:
            defaultMode: 420
            name: {{ $appName }}
          name: default-config
        - emptyDir: {}
          name: data
      containers:
        - name: {{ $appName }}
          image: "{{ $chart.Values.deployment.image.repository }}:{{ $chart.Values.deployment.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $chart.Values.deployment.image.pullPolicy | default $.Values.deployment.image.pullPolicy }}
          command: [ "/launcher" ]
          # command: ["/bin/sh"]
          # args: ["-c", "while true; do sleep 30; done"]
          volumeMounts:
            - mountPath: /dump
              name: heap-dumps
            - mountPath: /tmp
              name: tmp
            - mountPath: /logs
              name: logs
            - mountPath: /app/application.conf
              name: config
              subPath: application_config.json
            - mountPath: /app/static_jobs.json
              name: default-config
              subPath: static_jobs.json
            - mountPath: /launcher-config.yaml
              name: config
              subPath: launcher_config.yaml
            - mountPath: /mnt
              name: data
          resources:
            {{- $resources := $chart.Values.deployment.resources | default $.Values.deployment.resources }}
            {{- toYaml $resources | nindent 12 }}
          env:
            - name: K8S_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IMAGE_TAG
              value: {{ $chart.Values.deployment.image.tag | default $.Chart.AppVersion | quote }}
            {{- if $chart.Values.deployment.env }}
            {{- toYaml $chart.Values.deployment.env | nindent 12 }}
            {{- else if $.Values.deployment.env }}
            {{- toYaml $.Values.deployment.env | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ $chart.Values.deployment.containerPort | default $.Values.deployment.containerPort }}
              protocol: {{ if hasKey $chart.Values "service" }}{{ $chart.Values.service.protocol }}{{ else }}{{ $.Values.service.protocol }}{{ end }}
          {{- if $chart.Values.livenessProbe }}
          livenessProbe:
            {{- toYaml $chart.Values.livenessProbe | nindent 12 }}
          {{- else if $.Values.livenessProbe }}
          livenessProbe:
            {{- toYaml $.Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if $chart.Values.readinessProbe }}
          readinessProbe:
            {{- toYaml $chart.Values.readinessProbe | nindent 12 }}
          {{- else if $.Values.readinessProbe }}
          readinessProbe:
            {{- toYaml $.Values.readinessProbe | nindent 12 }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
