{{- $selected := .Values.subchart | default "" }}
{{- range $chartName, $chart := .Subcharts }}
  {{- if or (eq $selected "") (eq $chartName $selected) }}
    {{- $appName := $chartName | replace "isg-omcom-cassandra-scala-services-" "" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app: {{ $appName }}
  {{- with $chart.Values.annotations | default $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- /* First try to get service values from subchart, fall back to parent chart */}}
  type: {{ if hasKey $chart.Values "service" }}{{ $chart.Values.service.type }}{{ else }}{{ $.Values.service.type }}{{ end }}
  ports:
    - port: {{ if hasKey $chart.Values "service" }}{{ $chart.Values.service.port }}{{ else }}{{ $.Values.service.port }}{{ end }}
      targetPort: {{ if hasKey $chart.Values "service" }}{{ $chart.Values.service.targetPort }}{{ else }}{{ $.Values.service.targetPort }}{{ end }}
      protocol: {{ if hasKey $chart.Values "service" }}{{ $chart.Values.service.protocol }}{{ else }}{{ $.Values.service.protocol }}{{ end }}
      name: {{ if hasKey $chart.Values "service" }}{{ $chart.Values.service.portName }}{{ else }}{{ $.Values.service.portName }}{{ end }}
  selector:
    app: {{ $appName }}
  {{- end }}
{{- end }}
