# Application specific deployment configuration
global:
  appName: isg-omcom

deployment:
  replicaCount: 1
  image:
    repository: globe.pe.jfrog.io/isg-omcom-docker-local-nonprod/isg-omcom/dv/lf-auth-service
    tag: master-2025-06-13-0230-d7e1dde
    pullPolicy: IfNotPresent
  containerPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: 200m
      memory: 384Mi
  extraEnv:
    MESSAGE_ENABLE: "true"
    LOG_LEVEL: info
  envFrom:
    - secretRef:
        name: lf-auth-service-configuration
    - secretRef:
        name: petal-keycloak-credentials
