{{- range $chartName, $chart := .Subcharts }}
{{- if $chart.Values.deployment }}
{{- $appName := $chartName | replace "isg-omcom-cassandra-lua-services-" "" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app: {{ $appName }}
  {{- with $chart.Values.annotations | default $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $chart.Values.deployment.replicaCount | default $.Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
        {{- if and $chart.Values.deployment.image.tag }}
        lotusflare.com/tag: {{ $chart.Values.deployment.image.tag }}
        {{- end }}
      {{- with $chart.Values.podAnnotations | default $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with $chart.Values.deployment.imagePullSecrets | default $.Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        {{- $externalSecretEnabled := false }}
        {{- if $chart.Values.deployment.config }}
        {{- if $chart.Values.deployment.config.external_secret }}
        {{- if eq ($chart.Values.deployment.config.external_secret.enabled | toString) "true" }}
        {{- $externalSecretEnabled = true }}
        - name: external-secret-volume
          secret:
            secretName: {{ $appName }}-secret
        {{- end }}
        {{- end }}
        {{- else if $.Values.deployment.config }}
        {{- if $.Values.deployment.config.external_secret }}
        {{- if eq ($.Values.deployment.config.external_secret.enabled | toString) "true" }}
        {{- $externalSecretEnabled = true }}
        - name: external-secret-volume
          secret:
            secretName: {{ $appName }}-secret
        {{- end }}
        {{- end }}
        {{- end }}
      containers:
        - name: {{ $appName }}
          {{- if $chart.Values.deployment.image }}
          image: "{{ $chart.Values.deployment.image.repository }}:{{ $chart.Values.deployment.image.tag }}"
          imagePullPolicy: {{ $chart.Values.deployment.image.pullPolicy | default $.Values.deployment.image.pullPolicy }}
          {{- else }}
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent
          {{- end }}
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            {{- if $externalSecretEnabled }}
            - name: external-secret-volume
              mountPath: /mnt/lua/secrets.lua
              subPath: secrets.lua
              readOnly: true
            {{- end }}
          resources:
            {{- if $chart.Values.deployment.resources }}
            {{- toYaml $chart.Values.deployment.resources | nindent 12 }}
            {{- else if $.Values.deployment.resources }}
            {{- toYaml $.Values.deployment.resources | nindent 12 }}
            {{- end }}
          env:
            - name: K8S_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- if and $chart.Values.deployment.image.tag }}
            - name: IMAGE_TAG
              value: {{ $chart.Values.deployment.image.tag | quote }}
            {{- end }}
            {{- if $chart.Values.deployment.env }}
            {{- toYaml $chart.Values.deployment.env | nindent 12 }}
            {{- else if $.Values.deployment.env }}
            {{- toYaml $.Values.deployment.env | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ $chart.Values.deployment.containerPort | default $.Values.deployment.containerPort }}
              protocol: {{ if hasKey $chart.Values "service" }}{{ $chart.Values.service.protocol }}{{ else }}{{ $.Values.service.protocol }}{{ end }}
          {{- if $chart.Values.livenessProbe }}
          livenessProbe:
            {{- toYaml $chart.Values.livenessProbe | nindent 12 }}
          {{- else if $.Values.livenessProbe }}
          livenessProbe:
            {{- toYaml $.Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if $chart.Values.readinessProbe }}
          readinessProbe:
            {{- toYaml $chart.Values.readinessProbe | nindent 12 }}
          {{- else if $.Values.readinessProbe }}
          readinessProbe:
            {{- toYaml $.Values.readinessProbe | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}
