{{- range $chartName, $chart := .Subcharts }}
{{- $appName := $chartName | replace "isg-omcom-cassandra-lua-services-" "" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app: {{ $appName }}
  {{- with $chart.Values.annotations | default $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $chart.Values.service.type | default $.Values.service.type }}
  ports:
    - port: {{ $chart.Values.service.port | default $.Values.service.port }}
      targetPort: {{ $chart.Values.service.targetPort | default $.Values.service.targetPort }}
      protocol: {{ $chart.Values.service.protocol | default $.Values.service.protocol }}
      name: {{ $chart.Values.service.portName | default $.Values.service.portName }}
  selector:
    app: {{ $appName }}
{{- end }}
