{{- if .Values.serviceAccount.create -}}
{{- range $chartName, $chart := .Subcharts }}
{{- if $chart.Values.deployment }}
{{- $appName := $chartName | replace "isg-omcom-cassandra-polaris-services-" "" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
