{{- $selected := .Values.subchart | default "" }}
{{- range $chartName, $chart := .Subcharts }}
  {{- if or (eq $selected "") (eq $chartName $selected) }}
    {{- if $chart.Values.config }}
      {{- $appName := $chartName | replace "isg-omcom-cassandra-lua-services-" "" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app: {{ $appName }}
  {{- with $chart.Values.annotations | default $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- if $chart.Values.configFiles }}
  {{- range $fileName, $fileContent := $chart.Values.configFiles }}
  {{ $fileName }}: |
    {{- $fileContent | nindent 4 }}
  {{- end }}
  {{- end }}

  {{- if or $chart.Values.config $.Values.config }}
  lua_config.json: |
    {{- $config := dict }}

    {{- if $chart.Values.config }}
    {{- $config = merge $config $chart.Values.config }}
    {{- else }}
    {{- $config = merge $config $.Values.config }}
    {{- end }}

    {{- if $chart.Values.dependencies }}
    {{- $config = merge $config (dict "dependencies" $chart.Values.dependencies) }}
    {{- else if $.Values.dependencies }}
    {{- $config = merge $config (dict "dependencies" $.Values.dependencies) }}
    {{- end }}

    {{- $config | toPrettyJson | nindent 4 }}
  {{- end }}

  {{- if $chart.Values.nginx }}
  nginx.conf: |
    {{- $chart.Values.nginx | nindent 4 }}
  {{- else if $.Values.nginx }}
  nginx.conf: |
    {{- $.Values.nginx | nindent 4 }}
  {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
