{{- /*
  The logic is placed before the '---' separator to keep the generated YAML clean.
*/}}
{{- $selected := .Values.subchart | default "" }}
{{- range $chartName, $chart := .Subcharts }}
  {{- if or (eq $selected "") (eq $chartName $selected) }}
    {{- if $.Values.config }}
      {{- /* Create a safe copy of the parent config and merge the subchart config into it */}}
      {{- $mergedConfig := merge (deepCopy $.Values.config) $chart.Values.config -}}
      {{- $appName := $chartName | replace "isg-omcom-cassandra-lua-services-" "" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app: {{ $appName }}
  {{- with $chart.Values.annotations | default $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.lua: |
    local cjson = require "cjson.safe"
    local config = [[
    {{- /* Use the new mergedConfig variable here instead of the original one */}}
    {{- $mergedConfig | mustToPrettyJson | nindent 4 }}
    ]]

    return setmetatable({}, {
        __index = cjson.decode(config),
    })
    {{- end }}
  {{- end }}
{{- end }}
