# Application specific deployment configuration
deployment:
  image:
    repository: 637423436902.dkr.ecr.ap-southeast-1.amazonaws.com/isg-omcom/lf-images/lf-authorization
    tag: master-2025-06-09-2000-e369c06
    pullPolicy: IfNotPresent

externalSecret:
  annotations: {}

config:
  operators:
    - globecom
    - globecomexternal

  external_secret:
    enabled: true
    keys:
      common:
        - com.lotusflare.dno.braintree_prod.base_url

externalSecret:
  enabled: true
  annotations: {}
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager-store
    kind: ClusterSecretStore
  data:
    - secretKey: com_lotusflare_dno_braintree_prod_base_url
      remoteRef:
        key: isg/omcom/dv/cassandra/app/lua/secret-sm
        property: com.lotusflare.dno.braintree_prod.base_url
