# Application specific deployment configuration
deployment:
  image:
    repository: 637423436902.dkr.ecr.ap-southeast-1.amazonaws.com/isg-omcom/lf-images/lf-authorization
    tag: master-2025-06-09-2000-e369c06
    pullPolicy: IfNotPresent

config:
  service: authorization
  external_secret:
    enabled: true
    keys:
      common:
        - com.lotusflare.dno.braintree_prod.base_url

