global:
  appName: isg-omcom

# Global configurations shared across all applications
annotations: {}

# -- Exposed path for external domain
exposedPaths: []
extraServersConf: ""

# Global deployment defaults
deployment:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  containerPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  env: []

# Global probe configurations
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

# Global service configurations
service:
  type: ClusterIP
  protocol: TCP
  portName: http
  port: 80
  targetPort: 8080

config:
  operators:
    - globecom
    - globecomexternal

  external_secret:
    enabled: true
    keys:
      common:
        - com.lotusflare.dno.braintree_prod.base_url

externalSecret:
  enabled: true
  annotations: {}
  refreshInterval: 1h
  secretStoreRef:
    name: isg-omcom-dv-cassandra-app-lua-secret-sm
    kind: SecretStore
  data:
    - secretKey: com_lotusflare_dno_braintree_prod_base_url
      remoteRef:
        key: isg/omcom/dv/cassandra/app/lua/secret-sm
        property: com.lotusflare.dno.braintree_prod.base_url
