global:
  appName: isg-omcom

# Global configurations shared across all applications
annotations: {}

# -- Exposed path for external domain
exposedPaths: []
extraServersConf: ""

# Global deployment defaults
deployment:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  containerPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  env: []

# Global probe configurations
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

# Global service configurations
service:
  type: ClusterIP
  protocol: TCP
  portName: http
  port: 80
  targetPort: 8080

config:
  logging:
    class: logging.NgxLogSink
  cassandra:
    enabled: true
    hosts:
      - cassandra-1.isg-omcom-dv-cassandra-kns.svc.cluster.local
      - cassandra-2.isg-omcom-dv-cassandra-kns.svc.cluster.local
    log_slow_queries: false
    profiler_enabled: true
    retry_max: 3
    retry_on_timeout: true
    silent: false
    slow_query_threshold: "1000"
    specialized_clusters: {}
    timeout_connect: 4000
    timeout_read: "1500"
  k8_cluster_namespace: "isg-omcom-dv-cassandra-kns"
  custom_events:
    path_prefix: /mnt/lua/
  enable_task_scheduler_v2: true
  testpartnermvno1:
    overlay: mvne
  operators:
    - globecom
    - globecomexternal
  kafka_manager:
    broker_list:
      - host: kafka-0.dc22.lf
        port: 9092
      - host: kafka-1.dc22.lf
        port: 9092
      - host: kafka-2.dc22.lf
        port: 9092
    ssl: false
  kafka_logger_config:
    enable_kafka_produce_logs: true
    log_percent: 80
  redis:
    host: isg-omcom-dv-com-valkey-esv-y4vas7.serverless.apse1.cache.amazonaws.com:6379
    ssl: true
    pool_size: "15"
  redis_read_replica:
    hosts: dc22-elc-1-001.dc22-elc-1.kwsfrt.usw2.cache.amazonaws.com
  data_bucket_prefix: lf.aws-us-west-2-dc22.
  ssm_enabled: true
  external_secret:
    enabled: true
    keys:
      common:
        - com.lotusflare.dno.braintree_prod.base_url

externalSecret:
  enabled: true
  annotations: {}
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager-store
    kind: ClusterSecretStore
  data:
    - secretKey: com_lotusflare_dno_braintree_prod_base_url
      remoteRef:
        key: isg/omcom/dv/cassandra/app/lua/secret-sm
        property: com.lotusflare.dno.braintree_prod.base_url
