{{- $selected := .Values.subchart | default "" }}
{{- range $chartName, $chart := .Subcharts }}
  {{- if or (eq $selected "") (eq $chartName $selected) }}
    {{- if $chart.Values.deployment }}
      {{- $appName := $chartName | replace "isg-omcom-cassandra-polaris-services-" "" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app: {{ $appName }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $chart.Values.deployment.replicaCount | default $.Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
        lotusflare.com/tag: {{ $chart.Values.deployment.image.tag }}
    spec:
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $chart.Values.deployment.imagePullSecrets | default $.Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        {{- $externalSecretEnabled := false }}
        {{- $externalSecretConfig := $chart.Values.deployment.config.external_secret | default $.Values.deployment.config.external_secret }}
        {{- if $externalSecretConfig }}
        {{- if eq ($externalSecretConfig.enabled | toString) "true" }}
        {{- $externalSecretEnabled = true }}
        - name: external-secret-volume
          secret:
            secretName: {{ $appName }}-secret
        {{- end }}
        {{- end }}
        {{- if and .Values.extraVolumes .Values.extraVolumeMounts }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ $appName }}
          image: "{{ $chart.Values.deployment.image.repository }}:{{ $chart.Values.deployment.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $chart.Values.deployment.image.pullPolicy | default $.Values.deployment.image.pullPolicy }}
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            {{- if .Values.secrets }}
            - name: secrets
              mountPath: /etc/nginx/secrets
              readOnly: true
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml ($chart.Values.deployment.resources | default $.Values.deployment.resources) | nindent 12 }}
          env:
            - name: K8S_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IMAGE_TAG
              value: {{ $chart.Values.deployment.image.tag | quote }}
            {{- range $key, $value := ($chart.Values.deployment.env | default $.Values.deployment.env) | default dict }}
            - name: {{ $key }}
              {{- if kindIs "string" $value }}
              value: {{ $value | quote }}
              {{- else if kindIs "map" $value }}
              {{ toYaml $value | nindent 14 }}
              {{- else }}
              {{- end }}
            {{- end }}
            {{- range $key, $value := ($chart.Values.deployment.extraEnv | default $.Values.deployment.extraEnv) | default dict }}
            - name: {{ $key }}
              {{- if kindIs "string" $value }}
              value: {{ $value | quote }}
              {{- else if kindIs "map" $value }}
              {{ toYaml $value | nindent 14 }}
              {{- else }}
              {{- end }}
            {{- end }}
          {{- if .Values.deployment.envFrom }}
          envFrom:
            {{- toYaml .Values.deployment.envFrom | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ $chart.Values.deployment.containerPort | default $.Values.deployment.containerPort }}
          {{- with $.Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}
