{{- $selected := .Values.subchart | default "" }}
{{- range $chartName, $chart := .Subcharts }}
  {{- if or (eq $selected "") (eq $chartName $selected) }}
    {{- if $chart.Values.externalSecret }}
      {{- $appName := $chartName | replace "isg-omcom-cassandra-scala-services-" "" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app: {{ $appName }}
  {{- with $chart.Values.externalSecret.annotations | default $.Values.externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretStoreRef:
    name: {{ $chart.Values.externalSecret.secretStoreRef.name | default $.Values.externalSecret.secretStoreRef.name }}
    kind: {{ $chart.Values.externalSecret.secretStoreRef.kind | default $.Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ $appName }}-secrets
    creationPolicy: Owner
  data:
    {{- range $secretName, $secret := $chart.Values.externalSecret.data }}
    - secretKey: {{ $secretName }}
      remoteRef:
        key: {{ $secret.key }}
        property: {{ $secret.property | default $secretName }}
    {{- end }}
  {{- end }}
{{- end }}
