global:
  appName: isg-omcom

containerPort: 8080
securityContext: {}
config:
  external_secret:
    enabled: false
env: []
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /liveness
    port: http
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  httpGet:
    path: /readiness
    port: http
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1
startupProbe:
  httpGet:
    path: /startup
    port: http
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 60
  failureThreshold: 3
  successThreshold: 1

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
