global:
  appName: isg-omcom

# Global configurations shared across all applications
annotations: {}

# Global deployment
deployment:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  containerPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  env:
    AUTO_RUN_DB_MIGRATIONS: "true"
    TYPE_ORM_SYNCHRONIZE: "false"

# Global probe configurations
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

# Global service configurations
service:
  type: ClusterIP
  protocol: TCP
  portName: http
  port: 80
  targetPort: 8080

externalSecret:
  enabled: true
  refreshInterval: 5m
  secretStoreRef:
    name: isg-omcom-dv-cassandra-app-lua-secret-sm
    kind: SecretStore
  data:
    - secretKey: tmfc_configuration_service
      remoteRef:
        key: isg/omcom/dv/cassandra/app/polaris/secret-sm
        property: /tmfc/configuration/service
