{{- range $chartName, $chart := .Subcharts }}
{{- if $chart.Values.deployment }}
{{- $appName := $chartName | replace "isg-omcom-cassandra-scala-services-" "" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app: {{ $appName }}
  {{- with $chart.Values.annotations | default $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $chart.Values.deployment.replicaCount | default $.Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
        app.kubernetes.io/version: {{ $chart.Values.deployment.image.tag | default $.Chart.AppVersion }}
      {{- with $chart.Values.podAnnotations | default $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with $chart.Values.deployment.imagePullSecrets | default $.Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: heap-dumps
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: config
          configMap:
            name: {{ $appName }}
        - name: default-config
          configMap:
            name: {{ $appName }}
        - name: data
          emptyDir: {}
      containers:
        - name: {{ $appName }}
          image: "{{ $chart.Values.deployment.image.repository }}:{{ $chart.Values.deployment.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $chart.Values.deployment.image.pullPolicy | default $.Values.deployment.image.pullPolicy }}
          volumeMounts:
            - name: heap-dumps
              mountPath: /dump
            - name: tmp
              mountPath: /tmp
            - name: logs
              mountPath: /logs
            - name: config
              mountPath: "/app/application.conf"
              subPath: application_config.json
            - name: default-config
              mountPath: "/app/static_jobs.json"
              subPath: static_jobs.json
            - name: config
              mountPath: "/launcher-config.yaml"
              subPath: launcher_config.yaml
            - name: data
              mountPath: /mnt
          resources:
            {{- if $chart.Values.deployment.resources }}
            {{- toYaml $chart.Values.deployment.resources | nindent 12 }}
            {{- else if $.Values.deployment.resources }}
            {{- toYaml $.Values.deployment.resources | nindent 12 }}
            {{- end }}
          env:
            - name: K8S_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IMAGE_TAG
              value: {{ $chart.Values.deployment.image.tag | default $.Chart.AppVersion | quote }}
            {{- if $chart.Values.deployment.env }}
            {{- toYaml $chart.Values.deployment.env | nindent 12 }}
            {{- else if $.Values.deployment.env }}
            {{- toYaml $.Values.deployment.env | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ $chart.Values.deployment.containerPort | default $.Values.deployment.containerPort }}
              protocol: {{ if hasKey $chart.Values "service" }}{{ $chart.Values.service.protocol }}{{ else }}{{ $.Values.service.protocol }}{{ end }}
          {{- if $chart.Values.livenessProbe }}
          livenessProbe:
            {{- toYaml $chart.Values.livenessProbe | nindent 12 }}
          {{- else if $.Values.livenessProbe }}
          livenessProbe:
            {{- toYaml $.Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if $chart.Values.readinessProbe }}
          readinessProbe:
            {{- toYaml $chart.Values.readinessProbe | nindent 12 }}
          {{- else if $.Values.readinessProbe }}
          readinessProbe:
            {{- toYaml $.Values.readinessProbe | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}
