# Default values for omcom-lf-authorization
replicaCount: 1

image:
  repository: your-registry/omcom-lf-authorization
  pullPolicy: IfNotPresent
  tag: "" # Defaults to .Chart.AppVersion

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

env:
  []
  # - name: ENV_VAR_NAME
  #   value: "value"
