# Application specific deployment configuration
deployment:
  replicaCount: 1
  image:
    repository: globe.pe.jfrog.io/isg-omcom-docker-local-nonprod/isg-omcom/dv/lf-base-configuration-management
    tag: master-2025-06-13-0230-d7e1dde
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: isg-omcom-dv-jfrog-secret
  containerPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: 200m
      memory: 384Mi
