global:
  appName: isg-omcom

# Global configurations shared across all applications
annotations: {}

# Default deployment configuration that can be overridden by subcharts
deployment:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  containerPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  env: []

readinessProbe:
  exec:
    command:
      - bash
      - '-c'
      - wget -q -O - http://127.0.0.1:8080/metrics
  failureThreshold: 10
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 10

# Global service configurations
service:
  type: ClusterIP
  protocol: TCP
  portName: http
  port: 80
  targetPort: 8080

overrides:
  jarName: ""

clusters: {}

config:
  akka:
    http: # used by Alpakka S3
      client:
        idle-timeout: "5 minutes"
        connecting-timeout: "1 minute"
        stream-cancellation-delay: "30 seconds"
      host-connection-pool:
        response-entity-subscription-timeout: "30 seconds"
        client:
          idle-timeout: infinite
          stream-cancellation-delay: "30 seconds"
        max-open-requests: 512
  http:
    client:
      okhttp:
        connect-timeout: 30 seconds
        keep-alive-duration: 200 milliseconds
        max-idle-connections: 2
        max-requests: 128
        max-requests-per-host: 64
        read-timeout: 30 seconds
        write-timeout: 30 seconds
        compress-on-gzip-header: true
        debug-logging: true
        sensitive-headers:
          - Authorization
    host: 0.0.0.0
    port: 8080
  parameter-store:
    enabled: true
  additional-configs:
    enabled: false
    location: "/app/config"

launcher_config:
  Xms: 192m
  Xmx: 192m

  # This value has higher priority than XMS and XMX.
  # This feature is available with Java version >=8u191.
  # Values should be X.X, for example 25.0.
  # For more go to https://lotusflare.atlassian.net/browse/INFRA-1524
  RAMPercentage: "80.0"

  jmxremote_port: 30000

  # This will be appended to the list of predefined JVM options.
  jvm_options:
    # non-heap
    - "-Xss256k"
    - "-XX:+UseDynamicNumberOfGCThreads"
    - "-XX:InitiatingHeapOccupancyPercent=60"
    - "-XX:MaxMetaspaceSize=192m"
    - "-XX:CompressedClassSpaceSize=32m"
    - "-XX:ReservedCodeCacheSize=32m"
    - "-XX:MaxDirectMemorySize=64m"
    - "-XX:MinHeapFreeRatio=10"
    - "-XX:MaxHeapFreeRatio=15"
    - "-XX:GCTimeRatio=15"
    - "-XX:AdaptiveSizePolicyWeight=50"
    - "-XX:+UseStringDeduplication"
    - "-XX:+UseG1GC"
    - "-XX:MaxGCPauseMillis=10"

jobs: {}
