apiVersion: v2
name: cert-manager
description: Umbrella Helm chart for ArgoCD app
type: application
version: 1.0.0
appVersion: "1.16.0"
dependencies:
- name: cert-manager
  version: v1.14.5
  repository: https://charts.jetstack.io
  