cert-manager:
  global:
    leaderElection:
      # Override the namespace used to store the ConfigMap for leader election
      # The duration that non-leader candidates will wait after observing a
      # leadership renewal until attempting to acquire leadership of a led but
      # unrenewed leader slot. This is effectively the maximum duration that a
      # leader can be stopped before it is replaced by another candidate.
      leaseDuration: 60s
      # The interval between attempts by the acting master to renew a leadership
      # slot before it stops leading. This must be less than or equal to the
      # lease duration.
      renewDeadline: 40s
      # The duration the clients should wait between attempting acquisition and
      # renewal of a leadership.
      retryPeriod: 15s
  extraArgs:
    - --logging-format=json
  installCRDs: true
  replicaCount: 2
  resources:
    limits:
      cpu: 100m
      memory: 400Mi
    requests:
      cpu: 50m
      memory: 300Mi
  webhook:
    extraArgs:
      - --logging-format=json
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
  cainjector:
    extraArgs:
      - --logging-format=json
    replicaCount: 2
    resources:
      limits:
        cpu: 50m
        memory: 384Mi
      requests:
        cpu: 25m
        memory: 256Mi
  startupapicheck:
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
