# Global values shared between subchartsomcom-lf-apirequest:
replicas: 1
container:
  image:
    repository: globe.pe.jfrog.io/isg-gpayo-docker-local-nonprod/dv/gpayo-cms-frontend# Add apirequest specific overrides here

# Default values for omcom-lf-apirequest
replicaCount: 1
nameOverride: ""
fullnameOverride: ""

image:
  repository: your-registry/omcom-lf-apirequest
  tag: "0.1.0"
  pullPolicy: Always

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

service:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

env:
  tz: Asia/Jakarta

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

auth:
  irsa: read-write
