apiVersion: apps/v1
kind: Deployment
metadata:
  name: lf-apirequest # templatize this
  labels:
   app: lf-apirequest-container # templatize this
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: lf-apirequest-container # templatize this
  template:
    metadata:
      labels:
        app: lf-apirequest-container # templatize this
    spec:
      tolerations:                                                                                                                                                                                        
      - effect: NoSchedule                                                                                                                                                                                
        key: karpenter.sh/nodepool                                                                                                                                                                        
        operator: Equal                                                                                                                                                                                   
        value: isg-omcom-dv-np-omcom # templatize this
      affinity:                                                                                                                                                                                           
        nodeAffinity:                                                                                                                                                                                     
          requiredDuringSchedulingIgnoredDuringExecution:                                                                                                                                                 
            nodeSelectorTerms:                                                                                                                                                                            
            - matchExpressions:                                                                                                                                                                           
              - key: karpenter.sh/nodepool                                                                                                                                                                
                operator: In                                                                                                                                                                              
                values:                                                                                                                                                                                   
                - isg-omcom-dv-np-omcom # templatize this
      containers:
        - image: globe.pe.jfrog.io/isg-omcom-docker-local-nonprod/
          imagePullPolicy: IfNotPresent
          name: lf-apirequest-container
        #   command: ["/bin/sh", "-c", "echo 'Forcing the container to run infinitely'; sleep infinity"]
        #   resources:
        #     limits:
        #       cpu: 0.5m
        #       memory: 256Mi
      imagePullSecrets:
      - name: isg-omcom-dv-jfrog-secret
