# Application specific deployment configuration
deployment:
  replicaCount: 1
  image:
    repository: globe.jfrog.io/artifactory/isg-omcom-docker-local-nonprod/lf-base-configuration-management
    tag: master-2025-06-03-0944-89cb7a8
    pullPolicy: IfNotPresent
  containerPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: 200m
      memory: 384Mi
  env: []
