apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-utility
  labels:
   app: network-utility-container
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: network-utility-container
  template:
    metadata:
      labels:
        app: network-utility-container
    spec:
      # tolerations:                                                                                                                                                                                        
      # - effect: NoSchedule                                                                                                                                                                                
      #   key: karpenter.sh/nodepool                                                                                                                                                                        
      #   operator: Equal                                                                                                                                                                                   
      #   value: isg-atlas-dv-np-atlas
      # # affinity:                                                                                                                                                                                           
      #   nodeAffinity:                                                                                                                                                                                     
      #     requiredDuringSchedulingIgnoredDuringExecution:                                                                                                                                                 
      #       nodeSelectorTerms:                                                                                                                                                                            
      #       - matchExpressions:                                                                                                                                                                           
      #         - key: karpenter.sh/nodepool                                                                                                                                                                
      #           operator: In                                                                                                                                                                              
      #           values:                                                                                                                                                                                   
      #           - isg-atlas-dv-np-atlas
      containers:
        - image: globe.pe.jfrog.io/hmd-dockerhub/jonlabelle/network-tools
          imagePullPolicy: IfNotPresent
          name: network-utility-container
          command: ["/bin/sh", "-c", "echo 'Forcing the container to run infinitely'; sleep infinity"]
          resources:
            limits:
              cpu: 0.5m
              memory: 256Mi
      imagePullSecrets:
      - name: isg-omcom-dv-jfrog-secret
